---
title: "Section 3 and 4"
author: "Hailey Veirs"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

### Section 3 Tasks: 
Find the derivatives of the following:
$f(x)=x^2$ at x=3
$P(a)=2(3a+2)^4−5$ at a=1.2
$g(t)=−4t/(t2+1)^3$ at t=0

```{r}
# First name the expressions
fx <- expression(x ^ 2)

fx_prime <- deriv(fx, name = "x")
fx_prime
```

```{r}
Pa <- expression(2 * (3*a + 2) ^ 4 - 5)

Pa_prime <- deriv(Pa, name = "a")
Pa_prime
```

```{r}
gt <- expression((-4*t)/(t^2 + 1)^3)

gt_prime <- deriv(gt, name = "t")
gt_prime
```

## Section 4

Create a penguin scatterplot for bill length vs depth

```{r}
ggplot(penguins, aes(bill_length_mm, bill_depth_mm)) + 
  geom_point(aes(color = species)) + 
  labs(x = "Bill Length (mm)", 
       y = "Bill Depth (mm)", 
       title = "Penguin Bill Depth as a Function of Bill Length")

```

Now make a jitterplot of flipper length by species 

```{r}
ggplot(penguins, aes(species, flipper_length_mm)) + 
  geom_jitter(aes(color = species)) + 
  labs(x = "Species",
    y = "Flipper Length (mm)", 
    title = "Flipper Length of Different Species")
```

Remember to stage, commit, and push your files!
